import { I18n } from 'aws-amplify'
import { Translations } from "@aws-amplify/ui-components"

const languageDict = {
  ja: {
    [Translations.BACK_TO_SIGN_IN]: 'サインインに戻る',
    [Translations.CHANGE_PASSWORD_ACTION]: '変更',
    [Translations.CHANGE_PASSWORD]: 'パスワードを変更',
    [Translations.CODE_LABEL]: '確認コード',
    [Translations.CODE_PLACEHOLDER]: 'コードを入力',
    [Translations.SIGN_UP_CODE_LABEL]: 'ID(メールアドレス)',
    [Translations.CONFIRM_SIGN_UP_CODE_PLACEHOLDER]: 'コードを入力',
    [Translations.CONFIRM_SIGN_UP_CODE_LABEL]: '確認コード',
    [Translations.CONFIRM_SIGN_UP_HEADER_TEXT]: 'サインアップを確認',
    [Translations.CONFIRM_SIGN_UP_LOST_CODE]: '確認コードが見つかりませんか？',
    [Translations.CONFIRM_SIGN_UP_RESEND_CODE]: '確認コードを再送する',
    [Translations.CONFIRM_SIGN_UP_SUBMIT_BUTTON_TEXT]: '確認',
    [Translations.CONFIRM]: '確認',
    [Translations.CREATE_ACCOUNT_TEXT]: 'アカウントを作成',
    [Translations.EMAIL_LABEL]: 'ID(メールアドレス) *',
    [Translations.EMAIL_PLACEHOLDER]: 'Eメールアドレスを入力',
    [Translations.EMPTY_CODE]: '確認コードを入力してください',
    [Translations.FORGOT_PASSWORD_TEXT]: 'パスワードを忘れた場合',
    [Translations.NEW_PASSWORD_LABEL]: '新しいパスワード',
    [Translations.NEW_PASSWORD_PLACEHOLDER]: '新しいパスワードを入力',
    [Translations.NO_ACCOUNT_TEXT]: 'アカウントが未登録ですか？',
    [Translations.PASSWORD_LABEL]: 'パスワード *',
    [Translations.PASSWORD_PLACEHOLDER]: 'パスワードを入力',
    [Translations.RESET_PASSWORD_TEXT]: 'パスワードの再設定',
    [Translations.RESET_YOUR_PASSWORD]: 'パスワードリセット',
    [Translations.SELECT_MFA_TYPE_SUBMIT_BUTTON_TEXT]: '検証',
    [Translations.SEND_CODE]: '確認コード送信',
    [Translations.SUBMIT]: '送信',
    [Translations.SIGN_IN_ACTION]: 'サインイン',
    [Translations.SIGN_IN_HEADER_TEXT]: 'アカウントにサインイン',
    [Translations.SIGN_IN_TEXT]: 'サインイン',
    [Translations.SIGN_OUT]: 'サインアウト',
    [Translations.SIGN_UP_EMAIL_PLACEHOLDER]: 'Eメール',
    [Translations.SIGN_UP_HAVE_ACCOUNT_TEXT]: 'アカウントをお持ちですか？',
    [Translations.SIGN_UP_HEADER_TEXT]: '新しいアカウントを作成',
    [Translations.SIGN_UP_PASSWORD_PLACEHOLDER]: 'パスワード',
    [Translations.SIGN_UP_SUBMIT_BUTTON_TEXT]: 'アカウントを作成',
    [Translations.SIGN_UP_USERNAME_PLACEHOLDER]: 'ID(メールアドレス)',
    [Translations.TOTP_LABEL]: 'セキュリティコードを入力:',
    [Translations.USERNAME_LABEL]: 'ユーザー名 *',
    [Translations.USERNAME_PLACEHOLDER]: 'ユーザー名を入力',
    [Translations.VERIFY_CONTACT_EMAIL_LABEL]: 'Eメール',
    [Translations.VERIFY_CONTACT_SUBMIT_LABEL]: '送信',
    [Translations.VERIFY_CONTACT_VERIFY_LABEL]: '検証',
    
    // 上記定数と画面の文字が異なるため反映されないもの
    'Enter your Username': 'メールアドレス',
    'Forgot your password? ': 'パスワードを忘れた場合',
    'Lost your code? ': '確認コードが見つかりませんか？ ',
    'Code': '確認コード',
    'New Password': '新しいパスワード',
    'Enter your undefined': 'メールアドレス',

    // coginitoのエラーメッセージ
    'Invalid verification code provided, please try again.': '無効な確認コードです',
    'An account with the given email already exists.': 'このメールアドレスはすでに登録されています',
    'Username should be an email.': '正しい形式のメールアドレスを入力してください',
    'Username cannot be empty': 'メールアドレスを入力してください',
    'Custom auth lambda trigger is not configured for the user pool.': 'パスワードを入力してください',
    'User does not exist.': 'メールアドレスは登録されていません',
    'The following fields must be completed: Username': 'メールアドレスを入力してください',
    'The following fields must be completed: Username, Password': 'メールアドレスとパスワードを入力してください',
    'The following fields must be completed: Password': 'パスワードを入力してください',
    "1 validation error detected: Value at 'password' failed to satisfy constraint: Member must have length greater than or equal to 6": 'パスワードは6文字以上にしてください',
    'Username/client id combination not found.': 'このメールアドレスは登録されていません',
    'Incorrect username or password.': 'メールアドレスかパスワードが間違っています',
    'Password cannot be empty': 'パスワードを入力してください',
    'User password cannot be reset in the current state.': '現在の状態ではパスワードのリセットはできません',
    'Attempt limit exceeded, please try after some time.': '何度も確認コードを発行しています。少し待ってから再度試してください',
    'Password reset required for the user': 'パスワードの再設定を行って下さい',
    'Password did not conform with policy: Password not long enough': 'パスワードは8文字以上を入力してください',
    'Password does not conform to policy: Password not long enough': 'パスワードは8文字以上を入力してください',
    'Password did not conform with policy: Password must have lowercase characters': 'パスワードには英字を含めてください',
    'Password does not conform to policy: Password must have lowercase characters': 'パスワードには英字を含めてください',
    'Password did not conform with policy: Password must have numeric characters': 'パスワードには数字を含めてください',
    'Password does not conform to policy: Password must have numeric characters':'パスワードには数字を含めてください',
  }
}

I18n.putVocabularies(languageDict)
I18n.setLanguage('ja')
